import {test} from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createServer} from 'vite';
import {emptyProfile} from '../src/profile.mjs';
import {PET_NAMES} from '../src/data/roster.mjs';

test('Pets editor shows portraits and per-pet refinement inputs without ownership selection with shared effect headings and no activation controls',async t=>{
  const vite=await createServer({server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});
  t.after(()=>vite.close());
  const {App}=await vite.ssrLoadModule('/src/main.jsx');
  const p=emptyProfile();
  p.pets.find(pet=>pet.name==='Giant Rhino').owned=true;
  p.pets.find(pet=>pet.name==='Gray Wolf').owned=true;
  p.pets.find(pet=>pet.name==='Lynx').level=35;
  p.pets.push({id:'saved-utility',name:'Unmapped utility pet',owned:true,level:8,notes:'saved'});
  const html=renderToStaticMarkup(React.createElement(App,{initialTab:'Pets',initialProfile:p}));
  for(const name of [...PET_NAMES,'Unmapped utility pet'])assert.ok(html.includes(`aria-label="Show ${name} name"`),`${name} must have a row`);
  assert.ok(!html.includes('Lynx ownership'));
  assert.ok(!html.includes('class="pet-name"'));
  assert.ok(!html.includes('Refinement entry'));
  assert.ok(!html.includes('>Unknown</option>'));
  assert.ok(html.includes('Gray Wolf Infantry Lethality (%)'));
  assert.ok(html.includes('placeholder="Kingshot ID"'));
  assert.ok(!html.includes('Add a pet'));
  assert.ok(!html.includes('Remove Giant Rhino'));
  assert.ok(!html.includes('Wild Charge active for this hunt'));
  assert.ok(!html.includes('Use pet buffs for this hunt'));
  assert.ok(!html.includes('Exclude unavailable buffs'));
  assert.ok(html.includes('About pet effects'));
  assert.ok(html.includes('About pet levels'));
  assert.ok(html.includes('About Infantry pet refinement'));
  assert.ok(!html.includes('About Gray Wolf Infantry Lethality (%)'));
  const home=renderToStaticMarkup(React.createElement(App,{initialTab:'Home',initialProfile:p}));
  assert.ok(!home.includes('Activate your Bear pet buffs before starting.'));
  assert.ok(!html.includes('Gray Wolf Active for this hunt'));
  assert.ok(!html.includes('Cheetah Active for this hunt'));
  assert.ok(html.includes('Unmapped utility pet Level'));
  assert.equal(PET_NAMES.length,14);
  assert.equal((html.match(/class="pet-advancement-cell"/g)??[]).length,15);
  assert.ok(html.includes('>Advancement'));
  assert.ok(html.includes('value="0"'));
  assert.ok(html.includes('Not owned. Refinement is excluded.'));
  p.pets.find(pet=>pet.name==='Lion').level=60;
  p.pets.find(pet=>pet.name==='Grizzly Bear').level=60;
  p.pets.find(pet=>pet.name==='Giant Rhino').level=100;
  const milestones=renderToStaticMarkup(React.createElement(App,{initialTab:'Pets',initialProfile:p}));
  for(const label of ['Lion level 60 advanced at this level','Grizzly Bear level 60 advanced at this level','Giant Rhino level 100 advanced at this level'])assert.ok(milestones.includes(label),label);
  assert.ok(milestones.includes('Advanced at this level?'));
  assert.ok(!milestones.includes('pet-row-extra'));
  p.pets.find(pet=>pet.name==='Gray Wolf').level=50;
  p.pets.find(pet=>pet.name==='Gray Wolf').refinement={infantry:'1.50',cavalry:'2.010001',archer:'6.70'};
  const colored=renderToStaticMarkup(React.createElement(App,{initialTab:'Pets',initialProfile:p}));
  for(const color of ['#9cdaa7','#92caf3','#aeb5c5'])assert.ok(colored.includes('--refinement-color:'+color),color);
  assert.ok(!milestones.includes('Gray Wolf level 0 advanced at this level'));

});
