import {test} from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createServer} from 'vite';
import {emptyProfile} from '../src/profile.mjs';

test('Troops editor exposes shared actual capacity and compact inventory with optional preserved setup',async t=>{
 const vite=await createServer({server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});
 t.after(()=>vite.close());
 const {App}=await vite.ssrLoadModule('/src/main.jsx');
 const p=emptyProfile();p.hostCapacity=100000;p.joinCapacity=90000;
 const html=renderToStaticMarkup(React.createElement(App,{initialTab:'Troops',initialProfile:p}));
 for(const label of ['Quantity','Tier','Building TG','Maximum march size'])assert.ok(html.includes(label),label);
 for(const label of ['Infantry Quantity','Cavalry Quantity','Archers Quantity','Infantry maximum march count','Cavalry maximum march count','Archers maximum march count'])assert.ok(html.includes(label),label);
 for(const label of ['Total available','Fallback capacity entries mean','Derive march capacity from a base value','Include a hosting march','Rally capacity contribution:','Hero-free pusher','Pusher capacity','Different capacities per march','Troops per march','Setup adjustments','March setup','Available march slots','Joining marches','Join 1 leader','Join 2 leader','Join 3 leader','Infantry (%)','Cavalry (%)','Archers (%)','Saved capacities need confirmation'])assert.ok(!html.includes(label),label);
 assert.ok(!html.includes('fallback'));
 assert.ok(html.includes('>10/10/80</span>'));
 assert.ok(html.includes('troop-columns'));
 assert.ok(!html.includes('troop-capacity-options'));
 assert.ok(!html.includes('Full-capacity requirements'));
 assert.ok(!html.includes('Additional troops needed to fill all planned marches'));
 assert.ok(!html.includes('troop-plan-summary'));
 p.pusherEnabled=true;p.pusherCapacity=50000;p.marchSlots=5;
 p.joinCount=2;p.hostEnabled=false;
 const custom=renderToStaticMarkup(React.createElement(App,{initialTab:'Troops',initialProfile:p}));
 assert.ok(!custom.includes('Pusher capacity'));
 assert.ok(!custom.includes('Hero-free pusher'));
 const home=renderToStaticMarkup(React.createElement(App,{initialTab:'Home',initialProfile:p}));
 assert.ok(!home.includes('Hero-free pusher'));
 assert.ok(!home.includes('pusher capacity'));
 assert.ok(!custom.includes('troop-setup-options'));
 assert.ok(custom.includes('About Building TG'));
 assert.ok(custom.includes('Infantry Building TG'));
 assert.ok(!custom.includes('Saved Chenko'));
 assert.ok(!custom.includes('Full-capacity requirements'));
 const without=emptyProfile();without.troops.infantry.count=20000;without.troops.cavalry.count=30000;without.troops.archer.count=160000;
 const optional=renderToStaticMarkup(React.createElement(App,{initialTab:'Troops',initialProfile:without}));
 assert.ok(!optional.includes('Inventory-supported total:'));
 assert.ok(!optional.includes('Additional troops needed'));
 assert.ok(!optional.includes('Enter Maximum march size'));
});
